version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:6.1.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  rest-proxy:
#    image: confluentinc/cp-kafka-rest:6.1.0
#    depends_on:
#      - kafka
#    ports:
#      - "8082:8082"
#    hostname: rest-proxy
#    container_name: rest-proxy
#    environment:
#      KAFKA_REST_HOST_NAME: rest-proxy
#      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:9092'
#      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
#    networks:
#      - kafka-network

  postgres:
    image: hepsiburada/postgres:13.1-case
    ports:
      - "5432:5432"
    environment:
      - PGDATA=postgres
    networks:
      - kafka-network

  view-producer-app:
    build:
      context: ./ViewProducerApp
      dockerfile: Dockerfile
    container_name: view-producer-app
    environment:
      FILE_SOURCE: /assets/product-views-small.json
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: product-view
    restart: on-failure
    depends_on:
      - kafka
    networks:
      - kafka-network
    volumes:
      - ./assets:/assets
  
  stream-reader-app:
    build:
      context: ./StreamReaderApp
      dockerfile: Dockerfile
    container_name: stream-reader-app
    environment: 
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: product-view
      GROUP_ID: group1
    restart: on-failure
    depends_on: 
      - kafka
    networks: 
      - kafka-network

networks:
  kafka-network:
    name: kafka-network